networks:
  court_net:

volumes:
  sql_data:

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: yourStrong(!)Password
      ACCEPT_EULA: Y
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    networks:
        court_net:
    deploy:
      resources:
        limits:
          memory: 2G
  api:
    build:
      context: .
      dockerfile: CourtDemoProject.CaseManagementSystem.Api/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      CONNECTION_STRING: Server=sqlserver;Database=CaseManagementSystem;User Id=sa;Password=yourStrong(!)Password;TrustServerCertificate=true;
    depends_on:
      - sqlserver
    ports:
      - "8080:8080"
      - "8081:8081"
    networks:
        court_net:
    deploy:
      resources:
        limits:
          memory: 1G
  ui:
    build:
      context: .
      dockerfile: CourtDemoProject.CaseManagementSystem.Ui/Dockerfile
    depends_on:
      - sqlserver
      - api
    ports:
      - "80:80"
      - "443:443"
    networks:
        court_net:
    deploy:
      resources:
        limits:
          memory: 1G