using CourtDemoProject.CaseManagementSystem.Data.Enums;

namespace CourtDemoProject.CaseManagementSystem.Data.Dtos;
public record CaseParticipantDto(Guid CaseParticipantEntityId, CaseParticipantTypeEnum CaseParticipantType, string CaseParticipantFirstName, string CaseParticipantLastName, string CaseParticipantMiddleName);